my_shop_admin:
    resource: "@MyShopAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

my_shop_default:
    resource: "@MyShopDefaultBundle/Resources/config/routing.yml"
    prefix:   /

